version: '3'
services:
  apache:
    build: .docker/apache
    container_name: smartphones_apache
    ports:
    - 8080:80
    volumes:
    - .docker/config/vhosts:/etc/apache2/sites-enabled
    - .:/var/www/html/smartphones
    depends_on:
    - php

  mysqlDev:
    image: mysql:5.7
    container_name: smartphones_mysql_dev
    volumes:
    - .docker/data/db:/var/lib/mysql_dev
    ports:
    - 8090:3306
    environment:
      MYSQL_ROOT_PASSWORD: smartphones
      MYSQL_DATABASE: smartphones
      MYSQL_USER: smartphones
      MYSQL_PASSWORD: smartphones

  mysqlTest:
    image: mysql:5.7
    container_name: smartphones_mysql_test
    volumes:
      - .docker/data/db_test:/var/lib/mysql_test
    ports:
      - 8091:3306
    environment:
      MYSQL_ROOT_PASSWORD: smartphones
      MYSQL_DATABASE: smartphones_test
      MYSQL_USER: smartphones
      MYSQL_PASSWORD: smartphones

  php:
    build: .docker/php
    container_name: smartphones_php
    volumes:
    - .:/var/www/html/smartphones
    depends_on:
    - mysqlDev
    - mysqlTest